version: '3.8'

volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: donnavi/taski_backend:latest
    env_file: .env
    volumes:
      - static_volume:/backend_static

  frontend:
    image: donnavi/taski_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    
    image: donnavi/taski_gateway:latest
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80
